### ISSUE TITLE
VGA Not Work

### ISSUE THREAD

**Issue by apriady** [exxncss/x250-hackintosh#1]
Halo,
Sebelumnya terima kasih udah bikin repo ini, kebetulan saya ada x250 juga di rumah. Mau coba eksekusi hackintosh buat menggantikan macbook saya sementara selagi mau diservice.

Untuk masalah vga yg disebutkan di readme, boleh tau detail permasalahannya?

Thanks

**Comment by exxncss** [comment]
Sejujurnya blm saya coba, dan juga dari bbrp forum yang dibaca, memang tidak work krn VGA port tidak ada di real mac. Mungkin mas-nya bisa mencoba klo misalkan jadi install. solusi yg umum paling menggunakan mini DP (di kasus saya, mini dp colok ke converter HDMI, baru colok ke monitor external). Sekian~

**Comment by apriady** [comment]
Oh, yg dimaksud vga not work itu port D-Sub?
Kalau port d-sub biasanya memang tidak bisa sih mas.

Saya kira vga yg dimaksud itu GPU nya. 😅 

Minggu depan mungkin akan saya coba untuk eksekusi hackintosh di x250 saya. 👍🏻
