### ISSUE TITLE
Touchscreen  dose't wok

### ISSUE THREAD

**Issue by David3434** [exxncss/x250-hackintosh#2]
Hello
I'm using your clover on my x250 
It is working great except touchscreen
If possible make touchscreen alive too,or could you give some tips to make it 
I tried put some related drives from CLAY-BIOS to kexts folder, but it's failed

Thanks

**Comment by exxncss** [comment]
Hello there,
Sorry, my device wasn't touchscreen. So, I have no idea how to make it works in Clover.

Or maybe, you could try the OpenCore EFI and installing BigSur. There is proof that x250 touchscreen works perfectly. Here is the video https://www.youtube.com/watch?v=9E5M9qz4naQ. Cheers!

**Comment by David3434** [comment]
@exxncss 
ok, thank you
have a nice day 🤝
