### ISSUE TITLE
Audio and Battery Indicator not working (Big Sur)

### ISSUE THREAD

**Issue by axmad386** [exxncss/x250-hackintosh#3]
Sebelumnya terima kasih sudah membuat tutorial ini. Saya sudah coba sukses semua. termasuk Wifi. Joss
Hanya saja beberapa tidak bekerja, saya gunakan EFI yang OC dari release repo ini.
Apakah ada tahapan yang harus dilakukan?
Yang tidak bekerja:
 - Audio tidak ada suara
 - Battery Indicator tidak ada
 - klik kanan atau kiri hanya bisa pakai tombol yg diatas touchpad, tidak bisa pakai sentuh (misal klik kanan pakai dua jari klik kiri pakai 1 jari). Untuk scroll swipe kanan kiri bisa semua

**Comment by exxncss** [comment]
Halo, terimakasih utk feedback-nya
1. utk audio, apakah sudah dipastikan memakai layout-id 15?
2. untuk battery indicator, apakah battery-nya muncul atau tidak? sudah coba cek di system-preferences -> energy saver?
![Screen Shot 2020-10-27 at 15 35 17](https://user-images.githubusercontent.com/59009223/97276641-0ede9400-186a-11eb-8864-3c4dccd6984e.png)

3. untuk touchpad, apakah sudah disetting atau belom diapa-apakan?
![Screen Shot 2020-10-27 at 15 36 07](https://user-images.githubusercontent.com/59009223/97276703-23229100-186a-11eb-9121-cbc1e03fa8b1.png)

Dan satu lagi, apakah varian yang digunakan sama dgn punya saya? atau beda? contoh i3 atau i7? Ditunggu feedback selanjutnya! Salam

**Comment by axmad386** [comment]
Sepertinya ada yang aneh, punya saya i5
1. Untuk setting layout-id di mana ya? Maaf mas baru belajar
2. Ini dibagian energy saver mas
![Screen Shot 2020-10-27 at 16 53 52](https://user-images.githubusercontent.com/8775678/97285659-10618980-1875-11eb-9f0a-c6984b7c1a80.png)
kok nol persen punya saya
3. Ini bagian trackpad 
![Screen Shot 2020-10-27 at 16 55 26](https://user-images.githubusercontent.com/8775678/97285792-3b4bdd80-1875-11eb-8b09-556c3f583a99.png)

**Comment by axmad386** [comment]
oiya, saya pake bigsur beta 10. Apa harus yang beta 9?

**Comment by exxncss** [comment]
wah, sepertinya harus patching trackpad terlebih dahulu agar si battery jalan. terakhir saya coba di beta 9. klo beta 10 blm coba. dan di beta 9 works flawlessly sih mas. tapi mohon maaf, mungkin saya akan coba patching lagi ketika big sur release dikarenakan keterbatasan akses internet

**Comment by axmad386** [comment]
Oalah, oke mas. Terima kasih sebelumnya. Ya saya coba2 dulu dari forum2. Kalau nanti sudah ada patchnya kabar2 ya mas, hee. Sukses selalu mas

**Comment by exxncss** [comment]
Terima kasih atas feedback-nya!~

**Comment by apriady** [comment]
Saya juga mengalami issue mengenai baterai dan trackpad di BigSur, berikut logs yang muncul saat booting barangkali bisa membantu :

```[  332.094811]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPC.EC.GBIF] (Node ffffff9366996ab0)[\134_SB.PCI0.LPC.EC.GBIF] (Node ffffff9366996ab0), AE_AML_MUTEX_ORDER, AE_AML_MUTEX_ORDER (20160930/psparse-632)
[  332.094826]:  (20160930/psparse-632)
[  332.094833]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPC.EC.BAT0._BIF] (Node ffffff93669d90f0)[\134_SB.PCI0.LPC.EC.BAT0._BIF] (Node ffffff93669d90f0), AE_AML_MUTEX_ORDER, AE_AML_MUTEX_ORDER (20160930/psparse-632)
[  332.094847]:  (20160930/psparse-632)
[  332.094852]: ACPI Error: ACPI Error: Method parse/execution failed Method parse/execution failed [\134_SB.PCI0.LPC.EC.BATC._BIF] (Node ffffff9366996d20)[\134_SB.PCI0.LPC.EC.BATC._BIF] (Node ffffff9366996d20), AE_AML_MUTEX_ORDER, AE_AML_MUTEX_ORDER (20160930/psparse-632)
[  332.094865]:  (20160930/psparse-632)
[  332.098163]: SMCBatteryManager     acpib: @ battery 0 has no remaining capacity reported (0)
```

X250 milik saya memiliki internal battery, apakah itu juga yang turut mempengaruhi error tersebut?

**Comment by exxncss** [comment]
Halo @apriady, kebetulan saya juga memakai dual battery dan tidak ada masalah pada beta 9, tetapi banyak user yang mengeluhkan bahwa baterai dan trackpad tidak terpatch di beta 10. mungkin akan saya coba patching saat bigsur full release, karena skrg saya stay di catalina yang stabil utk urusan pekerjaan. cheers!

**Comment by axmad386** [comment]
@exxncss cuma mau kasih info, untuk audio punya saya sudah bisa mas. Pake model ALC292 sama layout_id 55. Yang baterai sama touchpad memang kayaknya peru dipatch. Saya belum paham untuk urusan patch2an, hehe

**Comment by exxncss** [comment]
terima kasih mas @axmad386 atas feedbacknya. oiya untuk mas @apriady, apakah sblm install BS sudah clear NVRAM?

**Comment by apriady** [comment]
> @exxncss cuma mau kasih info, untuk audio punya saya sudah bisa mas. Pake model ALC292 sama layout_id 55. Yang baterai sama touchpad memang kayaknya peru dipatch. Saya belum paham untuk urusan patch2an, hehe

Noise masih muncul gak mas kalau pake headset yg ada mic-nya?

> terima kasih mas @axmad386 atas feedbacknya. oiya untuk mas @apriady, apakah sblm install BS sudah clear NVRAM?

Sudah clear NVRAM dan juga installnya di storage baru yang kosong (storage lama yg catalina saya copot)

**Comment by exxncss** [comment]
> > @exxncss cuma mau kasih info, untuk audio punya saya sudah bisa mas. Pake model ALC292 sama layout_id 55. Yang baterai sama touchpad memang kayaknya peru dipatch. Saya belum paham untuk urusan patch2an, hehe
> 
> Noise masih muncul gak mas kalau pake headset yg ada mic-nya?
> 
> > terima kasih mas @axmad386 atas feedbacknya. oiya untuk mas @apriady, apakah sblm install BS sudah clear NVRAM?
> 
> Sudah clear NVRAM dan juga installnya di storage baru yang kosong (storage lama yg catalina saya copot)

Halo, barusan saya test di BigSur 11.0.1 Beta terbaru menggunakan EFI di repo ini (blm saya ganti apapun dalamnya), aman tidak ada kendala. Battery indicator, sound (alcid=15), dan trackpad berjalan mulus. Berikut gambarnya...

![Screen Shot 2020-11-02 at 13 47 15](https://user-images.githubusercontent.com/59009223/97838057-04147b00-1d12-11eb-92fc-49cbd70836e7.png)
![Screen Shot 2020-11-02 at 13 47 22](https://user-images.githubusercontent.com/59009223/97838073-0c6cb600-1d12-11eb-8601-22c4e1454766.png)
![Screen Shot 2020-11-02 at 13 47 33](https://user-images.githubusercontent.com/59009223/97838080-0ecf1000-1d12-11eb-814b-5cbd488edb6b.png)

Mungkin bisa dipastikan lagi bahwa sku laptop yang dipakai betul" sama dengan yang terlist di repo, untuk varian i3 dan i7 bisa ada perbedaan. dan juga, clear NVRAM untuk menghindari adanya bug dsb. Cheers!

**Comment by apriady** [comment]
@exxncss Noted, akan saya coba lagi setelah backup ke time machine.
Saya kabari disini hasilnya setelah eksekusi.
Terima Kasih.

**Comment by apriady** [comment]
@exxncss baru saja saya coba dengan BS 11.0.1 Beta, di laptop saya mendapat issue yang sama dengan kemarin.

**Comment by exxncss** [comment]
> @exxncss baru saja saya coba dengan BS 11.0.1 Beta, di laptop saya mendapat issue yang sama dengan kemarin.

bisa coba efi terbaru disini mas, barusan saya update ke oc 0.6.2 dengan kext terbaru. klo bisa clear nvram sebelum apply EFI baru-nya. semoga berhasil!

**Comment by axmad386** [comment]
@exxncss kalau upgrade ke 11.0.1 lewat AppStore bisa gk ya mas? Apa harus install ulang dari awal?

**Comment by exxncss** [comment]
> @exxncss kalau upgrade ke 11.0.1 lewat AppStore bisa gk ya mas? Apa harus install ulang dari awal?

Disarankan install ulang sih mas, tp klo mau coba ndak papa. fyi, tgl 10 bulan ini harusnya keluar final release BigSur hehe

**Comment by axmad386** [comment]
Wah nunggu finalnya aja berarti, hehe.
Iya mau install ulang tp kok download Giga2an. Wkwk
Pgen nyoba lewat App Store, barangkali bisa

**Comment by apriady** [comment]
> > @exxncss baru saja saya coba dengan BS 11.0.1 Beta, di laptop saya mendapat issue yang sama dengan kemarin.
> 
> bisa coba efi terbaru disini mas, barusan saya update ke oc 0.6.2 dengan kext terbaru. klo bisa clear nvram sebelum apply EFI baru-nya. semoga berhasil!

Oke, besok akan saya coba lagi.

Step untuk clear nvram yg benar itu sebelum booting installer di clear dulu, lalu booting ke usb installernya. Atau clear nvram saat udah booting pake usb installernya?

**Comment by exxncss** [comment]
> > > @exxncss baru saja saya coba dengan BS 11.0.1 Beta, di laptop saya mendapat issue yang sama dengan kemarin.
> > 
> > 
> > bisa coba efi terbaru disini mas, barusan saya update ke oc 0.6.2 dengan kext terbaru. klo bisa clear nvram sebelum apply EFI baru-nya. semoga berhasil!
> 
> Oke, besok akan saya coba lagi.
> 
> Step untuk clear nvram yg benar itu sebelum booting installer di clear dulu, lalu booting ke usb installernya. Atau clear nvram saat udah booting pake usb installernya?

klo step yg biasa saya lakukan, masuk installer, clear NVRAM, restart, baru install osnya hehe
