### ISSUE TITLE
Display port not work [Catalina]

### ISSUE THREAD

**Issue by endysuryo** [exxncss/x250-hackintosh#4]
Sebelumnya terimakasih sekali, x250 saya berhasi di install catalina, untuk driver wifi, audio, touchpad berjalan lancar.
tetapi saya mendapati blank screen ketika mau coba dual display lewat display port (bukan vga port), apakah ada solusi?

**Comment by exxncss** [comment]
[config1.plist.zip](https://github.com/exxncss/x250-hackintosh/files/5743174/config1.plist.zip)

dicoba mas, saya gabisa cek krn gaada monitor ext + conv. minidp. pastiin backup dulu config.plistnya

mohon utk feedback selanjutnya, cheers!

**Comment by endysuryo** [comment]
terimakasih mas, untuk minidpnya sudah work termasuk audionya

**Comment by endysuryo** [comment]
terimakasih mas, untuk minidpnya sudah bisa termasuk audionya
